apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: vertex-platform
type: Opaque
stringData:
  # JWT
  JWT_SECRET: "XLZxZMF4qdtjS6+t9IAOd5O+4fMwNqDRgwMtciTcVWleVCj3ebCIhAj1XgiQS9kfmiMmenPe2R9WZ9HGa05EKg=="

  # PostgreSQL (Neon)
  AUTH_DATABASE_URL: "postgres://neondb_owner:npg_GeqU0vPo3TaF@ep-flat-resonance-addiekdb-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require"

  # Redis
  REDIS_PASSWORD: "GvdJ1QHB3irE7634ehHXL+twKOQg/3rLzI6PwSkW4gs="

  # MongoDB
  MONGO_USERNAME: "platform_admin"
  MONGO_PASSWORD: "GvdJ1QHB3irE7634ehHXL+twKOQg/3rLzI6PwSkW4gs="

  # InfluxDB
  INFLUXDB_USERNAME: "admin"
  INFLUXDB_PASSWORD: "GvdJ1QHB3irE7634ehHXL+twKOQg/3rLzI6PwSkW4gs="
  INFLUXDB_TOKEN: "9t6y7G6Q5x66BfdbTwxsrC76qzCYkCDj/WXkU4EVet3x09+VZ6ilysF3GTQi9eTD"
